# Generated by Django 3.0.6 on 2020-05-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Location name is required'}, max_length=255)),
                ('x_coordinates', models.FloatField(error_messages={'required': 'Enter valid x coordinate'})),
                ('y_coordinates', models.FloatField(error_messages={'required': 'Enter valid y coordinate'})),
                ('description', models.TextField(error_messages={'required': 'Description is required'})),
                ('min_time', models.FloatField(error_messages={'required': 'Minimum time is required'})),
            ],
        ),
    ]
